/**
 * Markdown Renderer — SpecDocument / OrgSpecDocument → 단일 마크다운 문자열 변환
 */
import type { SpecDocument, OrgSpecDocument } from "./types.js";

export function renderSpecToMarkdown(doc: SpecDocument): string {
  const header = [
    `---`,
    `skillId: ${doc.skillId}`,
    `type: ${doc.type}`,
    `generatedAt: ${doc.generatedAt}`,
    `domain: ${doc.metadata.domain}`,
    `policyCount: ${doc.metadata.policyCount}`,
    `---`,
    "",
  ].join("\n");

  const sorted = [...doc.sections].sort((a, b) => a.order - b.order);
  const body = sorted.map((s) => s.content).join("\n\n---\n\n");

  const footer = [
    "",
    "---",
    "",
    `> Generated by Decode-X Spec Generator at ${doc.generatedAt}`,
    `> Skill: ${doc.skillId} | Domain: ${doc.metadata.domain} | Policies: ${doc.metadata.policyCount}`,
  ].join("\n");

  return `${header}\n${body}\n${footer}\n`;
}

export function renderOrgSpecToMarkdown(doc: OrgSpecDocument): string {
  const header = [
    `---`,
    `organizationId: ${doc.organizationId}`,
    `type: ${doc.type}`,
    `generatedAt: ${doc.generatedAt}`,
    `domain: ${doc.metadata.domain}`,
    `skillCount: ${doc.skillCount}`,
    `totalPolicies: ${doc.metadata.totalPolicies}`,
    `---`,
    "",
  ].join("\n");

  const sorted = [...doc.sections].sort((a, b) => a.order - b.order);
  const body = sorted.map((s) => s.content).join("\n\n---\n\n");

  const footer = [
    "",
    "---",
    "",
    `> Generated by Decode-X Org Spec Generator at ${doc.generatedAt}`,
    `> Org: ${doc.organizationId} | Domain: ${doc.metadata.domain} | Skills: ${doc.skillCount} | Policies: ${doc.metadata.totalPolicies}`,
  ].join("\n");

  return `${header}\n${body}\n${footer}\n`;
}
