name = "app-web"
pages_build_output_dir = "dist"
compatibility_date = "2025-01-01"

[vars]
ENVIRONMENT = "development"

# ---------------------------------------------------------------------------
# Staging environment
# ---------------------------------------------------------------------------
[env.staging]
vars = { ENVIRONMENT = "staging" }

# ---------------------------------------------------------------------------
# Production environment
# ---------------------------------------------------------------------------
[env.production]
vars = { ENVIRONMENT = "production" }
